name: Workflow
on: push

jobs:
  eslint:
    name: Run Lint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: yarn

      - name: Run eslint
        run: node_modules/eslint/bin/eslint.js -c .eslintrc src

  Test:
    name: Run Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x, 13.x]
        mongodb-version: [4.0, 4.2]

    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: yarn
      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.3.0
        with:
          mongodb-version: ${{ matrix.mongodb-version }}
      - run: yarn
      - run: node_modules/.bin/babel-node server.js
          env:
            CONNECTION_STRING: mongodb://mongodb:27017/sample
      - run: yarn test
